services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_USER: galixidb
      MARIADB_PASSWORD: galixidb
      # TODO: Need to have the password be configurable in the docker image, and then set here.

    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init-galixihub.sql:/docker-entrypoint-initdb.d/init-galixihub.sql:ro
      - galixihub-data:/var/lib/galixihub
      - galixihub-logs:/var/log/galixihub

    healthcheck:
      test: ["CMD", "mariadb", "-ugalixidb", "-pgalixidb", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 2

  galixihub:
    image: galixsysnetworks/galixihub:latest
    container_name: galixihub
    restart: "no"

    depends_on:
      mariadb:
        condition: service_healthy

    environment: 
      GALIXI_DB_HOST: mariadb

    volumes:
      - galixihub-data:/var/lib/galixihub
      - galixihub-logs:/var/log/galixihub
      - ../galixihub.env:/etc/galixihub/galixihub.env:ro  # Ensure container sees the same file

    # Ports mapping uses host variables exported from galixihub.env
    ports:
      - "${GALIXIHUB_PORT}-${GALIXIHUB_PORT_PLUS1}:${GALIXIHUB_PORT}-${GALIXIHUB_PORT_PLUS1}"

volumes:
  mariadb-data:
  galixihub-data:
  galixihub-logs:
